import api from '@/api/axios'
export const approvalsApi = {
  pendingLeave: () => api.get('/approvals/leave-requests/pending'),
  approveLeave: (id: number) => api.post(`/approvals/leave-requests/${id}/approve`),
  rejectLeave: (id: number, reason?: string) => api.post(`/approvals/leave-requests/${id}/reject`, { reject_reason: reason }),
  batchApproveLeave: (ids: number[]) => api.post('/approvals/leave-requests/batch-approve', { ids }),
  batchRejectLeave: (ids: number[], reason?: string) => api.post('/approvals/leave-requests/batch-reject', { ids, reject_reason: reason }),
  pendingPetition: () => api.get('/approvals/petitions/pending'),
  approvePetition: (id: number) => api.post(`/approvals/petitions/${id}/approve`),
  rejectPetition: (id: number, reason?: string) => api.post(`/approvals/petitions/${id}/reject`, { reject_reason: reason }),
  batchApprovePetition: (ids: number[]) => api.post('/approvals/petitions/batch-approve', { ids }),
  batchRejectPetition: (ids: number[], reason?: string) => api.post('/approvals/petitions/batch-reject', { ids, reject_reason: reason }),
  pendingAnnouncement: () => api.get('/approvals/announcements/pending'),
  approveAnnouncement: (id: number) => api.post(`/approvals/announcements/${id}/approve`),
  rejectAnnouncement: (id: number, reason?: string) => api.post(`/approvals/announcements/${id}/reject`, { reject_reason: reason }),
  batchApproveAnnouncement: (ids: number[]) => api.post('/approvals/announcements/batch-approve', { ids }),
  batchRejectAnnouncement: (ids: number[], reason?: string) => api.post('/approvals/announcements/batch-reject', { ids, reject_reason: reason }),
  pendingReport: () => api.get('/approvals/reports/pending'),
  approveReport: (id: number) => api.post(`/approvals/reports/${id}/approve`),
  rejectReport: (id: number, reason?: string) => api.post(`/approvals/reports/${id}/reject`, { reject_reason: reason }),
  batchApproveReport: (ids: number[]) => api.post('/approvals/reports/batch-approve', { ids }),
  batchRejectReport: (ids: number[], reason?: string) => api.post('/approvals/reports/batch-reject', { ids, reject_reason: reason }),
}
